version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /configs:/etc/nginx/conf.d
      - /certs:/etc/ssl/private

#   nginx-proxy-letsencrypt:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#     container_name: letsencrypt
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#     volumes_from:
#       - nginx-proxy

# networks:
#   default:
#     external:
#       name: nginx-proxy
