name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
      - name: SSH and Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "./docker-compose.yml,./setup.sh"
          target: "/proxy"
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sh setup.sh
